import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./services/context/auth/authContext";
import AuthWrapper from "./components/auth/authWrapper";
import { ProductContextProvider } from "./services/context/products/productsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <AuthWrapper>
            <ProductContextProvider>
              {children}
            </ProductContextProvider>
          </AuthWrapper>
        </AuthContextProvider>  
      </body>
    </html>
  );
}
